### PR TITLE
Add notebook for analyzing distances

### PR DESCRIPTION
**Pull request by pdeperio**
Based on @msekatchev's [analysis notebook](https://github.com/msekatchev/featureLabelling/blob/master/Dynode%20Centre%20Analysis/SK_Demo%20Projecting%20Dynode%20Centre.ipynb), with the following changes:

- Load results from pickle file (instead of re-running fit)
- Apply Kabsch transform (to ensure reco points as close as possible to expected)
- Change to simple single point comparisons (instead of projections)
  - Add radial/tangential comparison along expected radial vector

Note definition of "center point" depends on feature detection procedure, for example:
- May 2020 manually labeled the center of first dynode (so at that plane)
- March 2021 labeled at the center of the detected bolt ring (or visible PMT outline), so at the FRP flange (blacksheet) plane

### May 2020 Results
error-radial
error-tangential

### March 2021 Results
error-radial
error-tangential

### CODE REVIEW

**Review by msekatchev — APPROVED** [review]

**Comment by pdeperio** [comment]
Just replaced the analysis notebook to re-include the dynode projection onto bolt plane distances, so now should completely replace the original notebook linked above (except for some intermediate plotting of bolts).

Also just made some changes to the `SK_demo.ipynb`:
- Shift all seed points outward by 15 cm (based on consultation with Sekiya-san about SK geometry)
- Save output into pickle file that can be used in the analysis notebook

Note that I can't reproduce the Z-error of projection result that Michael presented at SK Calib with the fit output of this branch shown in the following figure:

### This branch
error-pmt_ProjectionZ

Compared to that from the fit produced by [Michael's branch](https://github.com/msekatchev/featureLabelling/blob/master/Dynode%20Centre%20Analysis/SK_Demo%20Projecting%20Dynode%20Centre.ipynb) (+ adding Kabsch transform) below:

### Michael's branch
error-pmt_ProjectionZ

So perhaps this previous slight indication of PMTs angled up relative to FRP was a coincidence. @nickwp @msekatchev not sure what's changed from [that fit](https://github.com/msekatchev/featureLabelling/blob/master/Dynode%20Centre%20Analysis/SK_Demo%20Projecting%20Dynode%20Centre.ipynb) and this one, but can this variation be expected?

**Comment by pdeperio** [comment]
could @msekatchev or @nickwp review quickly for merging so we have a state corresponding to SK Calib presentation?

**Comment by nickwp** [comment]
It looks like you've changed something in the old SK_demo.pynb, which was the old 24 PMT analysis, but should we be keeping that file consistent with the result we presented last May? It's shifting all the seed PMT radial positions in the notebook, but I don't think we should be doing that? Generally the logic for getting 'true' seed positions from the positions file (which corresponds to SKDETSIM positions, so I think should already correspond to the centre of the PMT, not the bolt ring?) should probably go in the sk_geo_tools.py file, which is used to generate the seed geometry. The code in that file already shifts the bolt ring's radial position relative to the PMT positions when generating the bolt positions, so if you want to do the opposite and shift PMT radial positions instead then I think that should also go in there, to avoid it being split between multiple places potentially leading to mistakes in relative positions.

**Comment by pdeperio** [comment]
1. We can modify `SK_demo.ipynb`, but indeed we should make a tag now to correspond to May 2020.

2. Indeed the latter, shifting PMT position, since Sekiya-san mentioned that the geometry file positions correspond to the FRP flange/BS plane (not PMT center), but also still awaiting Kameda-san's confirmation. Anyways, now that I have more time to think about it, I guess it's translating the endcap PMTs completely wrong. How did you treat the endcap bolts? I'll remove this change from this PR and create a new issue.

**Comment by pdeperio** [comment]
OK now only change in `SK_demo.ipynb ` is the saving to pickle file, required for the analysis notebook.

Copying the old shift code here for future reference:
```
# Shift dynode position 15cm radially outward from geometry file position that corresponds to FRP flange/BS plane
pmt_dynode_offset = 15
for value in all_pmt_locations.values():
    phi = np.arctan2(value[1], value[0])
    value[0] = value[0] + pmt_dynode_offset * np.cos(phi)
    value[1] = value[1] + pmt_dynode_offset * np.sin(phi)
```

**Comment by nickwp** [comment]
> I guess it's translating the endcap PMTs completely wrong. How did you treat the endcap bolts?

Right, the endcap bolts are not treated at all currently: [the function](https://github.com/WatChPhoto/PhotogrammetryAnalysis/blob/master/sk_geo_tools.py#L10) for generating bolt locations is named `get_bolt_locations_barrel` and there's no corresponding function for end-caps yet.
> Sekiya-san mentioned that the geometry file positions correspond to the FRP flange/BS plane (not PMT center)

That's interesting... so does SKDETSIM take this into account when placing the PMTs? If so, can we find out what the assumed distance is from PMT centre as it's placed in SKDETSIM to FRP flange as it's defined in the position file? Is it exactly the 15cm you used as your shift?

**Review by nickwp — APPROVED** [review]

**Review by msekatchev — APPROVED** [review]

**Pull request merged**
