### PR TITLE
Lots of updates to analysis code

### PR DESCRIPTION
**Pull request by nickwp**

### CODE REVIEW

**Review by pdeperio — CHANGES_REQUESTED** [review]
quick comment before more thorough review: try not to store large binaries (e.g. `JPG`, `png`), makes repo bulky. link to [the server](http://neutsrv2.triumf.ca/neutshare/superk/TOW-Feb2020/Labels/Manual/BarrelSurveyFar_TopInjector_PD3/BarrelSurveyFar_TopInjector_median) instead in any instructions or `sourceme` download scripts.

**Comment by pdeperio** [comment]
also, `png`s not needed?

**Comment by nickwp** [comment]
None of the image files are needed. I removed the jpgs. What pngs?

**Comment by pdeperio** [comment]
the masks

**Comment by nickwp** [comment]
no, dont need any of them, I just removed the folders with the images

**Comment by pdeperio** [comment]
there's some in `BarrelSurveyFar_TopInjector_Labeled` still. (i guess this whole folder was the first set `PD1`?)

**Comment by nickwp** [comment]
thanks, removed those too

**Review by pdeperio — APPROVED** [review]

**Pull request merged**
