### PR TITLE
Reorganize input and output files

### PR DESCRIPTION
**Pull request by pdeperio**
Created new folders
`results`: Output tables of camera and feature parameters
`parameters`: Input PMT positions, calibration parameters, etc.
and moved files and paths in scripts accordingly.

(@nickwp: please review, approve, merge, and delete branch. i should not do my own PRs for good practice!)

### CODE REVIEW

**Review by nickwp — APPROVED** [review]

**Comment by pdeperio** [comment]
thanks. please merge&delete

**Comment by nickwp** [comment]
I don't have permission on this fork. If you can merge this then I can pull it into my fork and update #3

**Comment by pdeperio** [comment]
oh sorry, try now

**Comment by nickwp** [comment]
still says "Only those with write access to this repository can merge pull requests"

**Comment by nickwp** [comment]
oh it's working now

**Pull request merged**
