### PR TITLE
Updates to code and SK demo

### PR DESCRIPTION
**Pull request by nickwp**

### CODE REVIEW

**Comment by pdeperio** [comment]
`SK_ring_simulation-Copy1.ipynb` vs `SK_ring_simulation.ipynb`?

**Comment by pdeperio** [comment]
looks like mainly just 12 bolt vs 24?

**Comment by nickwp** [comment]
yeah, honestly I think the copy was committed by mistake

**Comment by nickwp** [comment]
pushed a change with some more updates to the simulation notebooks and removing that copy notebook

**Comment by nickwp** [comment]
Okay, it's basically up to date now with my local copy too, although still could do with more cleaning up I think that's not worth waiting for but can be sorted later and as a separate PR

**Pull request merged**
